#
# SPDX-License-Identifier: Apache-2.0
#
---
pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "status-success=IBM-Blockchain.ansible-role-blockchain-platform-manager"
      - "status-success=DCO"
    actions:
      merge:
        method: merge
        strict: true
        strict_method: merge