#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Get the list of components
  uri:
    url: "{{ infrastructure.saas.api_endpoint }}/ak/api/v1/components"
    method: GET
    return_content: yes
    headers:
      Authorization: "Bearer {{ ibp.saas.access_token }}"
  register: ibp_components

- name: Check for peer
  set_fact:
    ibp_peer_count: "{{
      ibp_components.json |
      selectattr('display_name', 'defined') |
      selectattr('display_name', 'eq', peer.ibp.display_name) |
      list
    }}"

- name: Delete peer
  uri:
    url: "{{ infrastructure.saas.api_endpoint }}/ak/api/v1/components/{{ ibp_peer.id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ ibp.saas.access_token }}"
  changed_when: True
  with_items: "{{ ibp_peer_count }}"
  loop_control:
    loop_var: ibp_peer